# marker map grid
# copy from pairwise_interactions.R

rm(list=ls())
setwd('~/Desktop/Exosome Special Edition/')
library(data.table); library(stringi)
file_list <- list.files(pattern="*.csv")
# get rid of unwanted file from pattern search (this is a clunky hack)
tfl <- file_list[!file_list=="full_marker_node_set.csv"]; rm(file_list)
fmns <- fread('full_marker_node_set.csv',header=T)

# Create empty list and load it with dataframes listed in file_list
veclist <- list()
for (i in 1:length(tfl)) {
	veclist[[i]] <- fread(paste(tfl[i]))
	# Reduce df to a vector of DOIs
	veclist[[i]] <- veclist[[i]]$DOI
	# remove any empty strings generated by Scopus
	# to prevent counting them as DOIs
	veclist[[i]] <- stri_remove_empty(veclist[[i]])
}
# simplify names
short_names <- sapply(strsplit(tfl,"_"), `[`, 1)
# Loop through tfl and add columns to full_marker_node_list
for (i in 1:length(veclist)) {
	fmns[x %in% veclist[[i]],paste(short_names[i]):=1]
}
# replace NAs with 0
fmns[is.na(fmns)] <- 0
# calculate rowSums for columns 3-14
rsnames <- colnames(fmns)[3:14]
fmns[,rs:=rowSums(.SD), .SDcols = rsnames]
fmns[,V1:=NULL]
colnames(fmns)[1] <- "doi"
fwrite(fmns,file='marker_map_grid.csv')
