# Script to calculate pairwise intersections, total intersection, and union of references from 
# exosome reviews: Stahl Collection
# George Chacko Sep 10, 2021: run on my laptop: the data are also on valhalla

rm(list=ls())
setwd('~/Desktop/Exosome Special Edition/')
library(data.table); library(stringi)
file_list <- list.files(pattern="*.csv")
# get rid of unwanted file (this is a clunky hack)
#file_list <- filelist[!filelist==filelist[10]]; rm(filelist)

# Create empty list and load it with dataframes listed in file_list
veclist <- list()
for (i in 1:length(file_list)) {
	veclist[[i]] <- fread(paste(file_list[i]))
	# Redeuce df to a vector of DOIs
	veclist[[i]] <- veclist[[i]]$DOI
	# remove any empty strings generated by Scopus
	# to prevent counting them as DOIs
	veclist[[i]] <- stri_remove_empty(veclist[[i]])
}
# label the list elements (dataframes) from file_list
names(veclist) <- paste(file_list); rm(i)
# generate vector name pairs for visual inspection
combn(names(veclist), 2)

# generate pairwise intersections of DOIs from vectors in veclist
ilist <- combn(veclist, 2, function(x) intersect(x[[1]], x[[2]]), simplify = F)
# manually check at least 5 pairs
# generate vector of intersections
intersections <- unlist(lapply(ilist,length))
# create empty 12 x 12 matrix 
b <- matrix(0,12,12)
# copy intersections vector into lower triangle of matrix
b[lower.tri(b, diag=FALSE)] <- intersections
#transpose b
b <- t(b)
# use function from Stack Overflow
# https://stackoverflow.com/questions/28746023/how-to-insert-values-from-a-vector-diagonally-into-a-matrix-in-r/28746375#28746375 
insert.diag <- function(A,b,start=c(1,1),dir=c(1,1)) {
  sq <- seq_along(b)-1
  indices <- sapply(1:2,function(i) start[i] + dir[i]*sq)
  stopifnot(all(indices>0))
  stopifnot(all(indices[,1]<=nrow(A)))
  stopifnot(all(indices[,2]<=ncol(A)))  
  A[indices] <- b
  A
}
# make vector for diagonal
diag <- unname(unlist(lapply(veclist,length)))
# insert diag into matrix b
m <- insert.diag(b,diag,c(1,1),c(1,1))
# optional set lower triangle to zero
library(gdata)
lowerTriangle(m) <- NA

#convert matrix into human readable dataframe
m_df <- as.data.frame(m)
short_names <- sapply(strsplit(file_list,"_"), `[`, 1)
# make a copy of m_df to change colnames etc, into human readable (hr)
hr_m_df <- m_df
colnames(hr_m_df) <- paste(short_names)
row.names(hr_m_df) <- paste(short_names)
# optional replace zeros with NA (this can be problematic if some intersection values are zero
# instead just set the lowerTriangle to NA as above)
# hr_m_df[hr_m_df==0] <- NA

# Union of contents of all 10 sets of references
union_vec <- unique(unname(unlist(veclist, recursive = FALSE)))
# Intersection of contents of all 10 sets of references
Reduce(intersect,veclist) # returns an empty character vector
# This approach can be tested as follows
veclist2 <- veclist
for (i in 1:length(veclist2)) {
	veclist2[[i]] <- append(veclist[[i]],'abc')
}
temp <- file_list[-6] # remove kalluri reviews since they're a subset
print(paste("The total number of references in the 11 articles is", sum(sum(unlist(lapply(veclist,length))) -55)))
# subtract 55 (above since they're redundant in kalluri's references)
Reduce(intersect,veclist2)
# returns [1] "abc"
xtable(hr_m_df)


